version: '3.8'

services:
  app:
    image: wfelipe2011/finance:master
    ports:
      - '7000:7000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M